substitutions:
  _IMAGE_NAME: 'asia-southeast2-docker.pkg.dev/bangkit-capstone-441617/finsight-api/finsight-api'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE_NAME:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE_NAME:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy finsight-api \
          --image $_IMAGE_NAME:$COMMIT_SHA \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated \
          --mount-secret volume=finsight-env-secret:/secrets/finsight-env-secret
options:
  logging: CLOUD_LOGGING_ONLY
