substitutions:
  _IMAGE_NAME: 'asia-southeast2-docker.pkg.dev/bangkit-capstone-441617/finsight-api/finsight-api'
  _ENV_SECRET_NAME: 'finsight-env-secret'
  _CREDENTIAL_SECRET_NAME: 'finsight-profile-bucket'

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE_NAME:latest', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE_NAME:latest']

  # Step 3: Fetch and process environment variables secret
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching environment variables secret..."
        ACCESS_TOKEN=$(gcloud auth print-access-token)
        RAW_SECRET=$(curl -H "Authorization: Bearer $ACCESS_TOKEN" \
                         "https://secretmanager.googleapis.com/v1/projects/$PROJECT_ID/secrets/$_ENV_SECRET_NAME/versions/latest:access" \
                         | jq -r '.payload.data' | base64 --decode)
        
        # Remove commas and create .env-style format
        echo "$RAW_SECRET" | tr -d ',' > $BUILD_ID-secrets.env

  # Step 4: Fetch service account credential as JSON
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching service account credential secret..."
        ACCESS_TOKEN=$(gcloud auth print-access-token)
        CREDENTIAL_SECRET=$(curl -H "Authorization: Bearer $ACCESS_TOKEN" \
                               "https://secretmanager.googleapis.com/v1/projects/$PROJECT_ID/secrets/$_CREDENTIAL_SECRET_NAME/versions/latest:access" \
                               | jq -r '.payload.data' | base64 --decode)
        
        echo "$CREDENTIAL_SECRET" > $BUILD_ID-service-account.json

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy finsight-api \
          --image $_IMAGE_NAME:latest \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars-file $BUILD_ID-secrets.env \
          --set-secrets SERVICE_ACCOUNT_JSON=$BUILD_ID-service-account.json

options:
  logging: CLOUD_LOGGING_ONLY
